calibr:
  chessboard_size: (7, 6)
camera:
  height: 480
  width: 640
filter_kps:
  ret_pts: 600
  tol: 0.1
frames:
  chosen_id: 24_jul_2022_16_59_00
  folder_ids:
  - 19_jul_2022_18_44_01
  - 19_jul_2022_18_48_49
  - 19_jul_2022_18_56_53
  - 19_jul_2022_19_02_10
  - 22_jul_2022_19_49_39
  - 24_jul_2022_12_49_37
  list_timestamps:
  - 19_jul_2022_18_48_49
  path_obj: data/rgbd/19_jul_2022_18_48_49/images/
key_press:
  '110': 1
  '98': -1
mode: framebyframe # calibration, realtime, framebyframe
new_timestamp: 24_jul_2022_16_52_00
orb_features:
  n_feats: 600
